# Assignment 3: Advanced Python (30 pt)

This assignment covers materials from the material on loops, functions, and NumPy lectures.

Note that these questions are longer and somewhat more open ended than previous assignments. Please reach out if you need assistance getting started.

Feel free to create as many Python or Markdown cells as you desire to answer the questions.

## Question 1: For loops (10 pts)

Below, we have a nested dictionary structure containing information about several species ranging from vulnerable to critically endangered. Note than in some cases, species populations are listed as `None`. This means that the wild populations of these species are unknown. 

Use for loops to accomplish the following tasks: 

- Create a data structure containing all unique types of "Threats". This variable should not contain duplicate entries. Print the structure (2 pt).
- Create a list of all of the species listed as "Critically Endangered". Print the list (2 pt).
- Create a separate list containing the names of species with populations with fewer than 50 individuals and species with unknown population sizes. Print the list (3 pt).
- Find the species with the largest population size. Print this species name, and what its population size is (3 pt).

If you hard code the solutions (e.g. manually pick out which species has the largest population) you will receive NO points.

In [58]:
conservation_data = {
    "Giant Panda": {
        "Status": "Endangered",
        "Population": 1800,
        "Threats": ["Habitat loss", "Poaching"]
    },
    "Mountain Gorilla": {
        "Status": "Critically Endangered",
        "Population": 1063,
        "Threats": ["Habitat loss", "Poaching", "Civil unrest"]
    },
    "Amur Leopard": {
        "Status": "Critically Endangered",
        "Population": 84,
        "Threats": ["Habitat loss", "Poaching"]
    },
    "Vaquita": {
        "Status": "Critically Endangered",
        "Population": 10,
        "Threats": ["Bycatch in fishing nets"]
    },
    "African Elephant": {
        "Status": "Vulnerable",
        "Population": 415000,
        "Threats": ["Habitat loss", "Poaching"]
    },
    "Javan Rhino": {
        "Status": "Critically Endangered",
        "Population": 72,
        "Threats": ["Habitat loss", "Poaching"]
    },
    "Sumatran Orangutan": {
        "Status": "Critically Endangered",
        "Population": 14600,
        "Threats": ["Habitat loss", "Poaching"]
    },
    "Hawksbill Turtle": {
        "Status": "Critically Endangered",
        "Population": None,
        "Threats": ["Habitat loss", "Poaching"]
    },
    "Saola": {
        "Status": "Critically Endangered",
        "Population": None,
        "Threats": ["Habitat loss", "Poaching"]
    },
    "Iberian Lynx": {
        "Status": "Endangered",
        "Population": 94,
        "Threats": ["Habitat loss", "Poaching"]
    }
}

In [59]:
threats = set()
critically_endangered = []
low_pop = []
largest_pop = 0
largest_species = ""
for species in conservation_data: # Iterates over outer dictionary
    for key in conservation_data[species].keys(): # Iterates over inner dictionary
        # Finds all of the critically endangered species and adds them to a list
        if key == "Status" and conservation_data[species][key] == "Critically Endangered":
            critically_endangered.append(species)
        
        # Checks the population cases
        if key == "Population":
            if conservation_data[species][key] is None or conservation_data[species][key] < 50:
                low_pop.append(species)
            if conservation_data[species][key] is not None and conservation_data[species][key] > largest_pop:
                largest_pop = conservation_data[species][key]
                largest_species = species
        # Finds all of the threats to all of the animals and adds them to a set
        if key == "Threats":
            # Iterates over the list of threats for each species
            for i in range(len(conservation_data[species][key])):
                threats.add(conservation_data[species][key][i])

print(threats)
print(critically_endangered)
print(low_pop)
print(largest_species + ": " + str(largest_pop))

{'Bycatch in fishing nets', 'Civil unrest', 'Poaching', 'Habitat loss'}
['Mountain Gorilla', 'Amur Leopard', 'Vaquita', 'Javan Rhino', 'Sumatran Orangutan', 'Hawksbill Turtle', 'Saola']
['Vaquita', 'Hawksbill Turtle', 'Saola']
African Elephant: 415000


## Question 2: Functions (10 pt)

When considering the health of an ecosystem, an important concept to quantify is the diversity of that system. There are several metrics commonly used to calculate ecosystem diversity, one of which is call Simpson's Diversity Index.

This metric not takes into account how many species are present in an location, but also if one species has far more individuals than other species. For example, an ecosystem with 500 species but only one species above 10 individuals is not that diverse.

We can calculate Simpson's Diversity ($D$) as follows:

$D = 1 - [(\frac{n_1}{N})^2 + (\frac{n_2}{N})^2 + (\frac{n_3}{N})^2 + ...]$

For example, if an ecosystem has four species with 5, 2, 2, and 1 individuals (10 individuals total), you can calculate $D$ like this:

$D = 1 - [(\frac{5}{10})^2 + (\frac{2}{10})^2 + (\frac{2}{10})^2 + (\frac{1}{10})^2] = 0.66$

Define a function that calculates and returns $D$ given a list of species population levels, and run the function on several example lists (3 pt).

Your answer should work for a list of **any** length (1 pt).

Add documentation to the function that describes what it does, the desired parameters, and what data types the parameters should be (2 pt).

Within the function, check that the input is a list. If the input is not a list, give a custom error message (2 pt).

Also, make sure all entries in the list are integers. If there are floats, convert them to integers. If there are entries that are not floats or integers, give a custom error message (2 pt).



In [60]:
example_input = [1882, 400, 321, 24]
example_1 = [5, 2, 2, 1]
not_a_list = {}
not_a_list2 = 0
contains_floats = [0.5, 4, 0.96, 3]
contains_strings = ["hello", 5, 6, 7, "world"]
large_input = [conservation_data[species][key] for species in conservation_data for key in conservation_data[species].keys() if key == "Population" and conservation_data[species][key] is not None]
print(large_input)

def simpsons_diveristy(pop_list):
    '''
    Input: A list of integers which represent the populations of various species in an ecosystem
    Output: A float d, which is Simpson's Diversity calculated on the input list.
    '''
    d = 1
    sum = 0
    
    # Checks if input is a list
    if type(pop_list) != list:
        return "Error: Item is not a list"
    
    # Iterates over the list and find the total population of the ecosystem
    for pop in range(len(pop_list)):
        current_pop = pop_list[pop]
        if type(current_pop) != int: # Checks if the element is an int
            if type(current_pop) == float:
                current_pop = int(current_pop) # If the element is a float it is converted to an int
            else:
                return "Error: List contains elements of the wrong type"
        sum += current_pop

    # Iterates over the list and calculates d
    for species in range(len(pop_list)):    
        d -= (pop_list[species]/sum) ** 2
    return d

print (simpsons_diveristy(example_input))
print (simpsons_diveristy(example_1))
print (simpsons_diveristy(not_a_list))
print (simpsons_diveristy(not_a_list2))
print (simpsons_diveristy(contains_floats))
print (simpsons_diveristy(contains_strings))
print (simpsons_diveristy(large_input))


[1800, 1063, 84, 10, 415000, 72, 14600, 94]
0.44856254679487945
0.6599999999999999
Error: Item is not a list
Error: Item is not a list
0.46588571428571446
Error: List contains elements of the wrong type
0.07907453810644789


## Question 3: Simulating data (10 pt)

In data analysis, we often simulate data to help test our predictions and get a feel for how the real data should be. This questions asks you to use the functions found in `numpy.random` to simulate rolling.

Define a function called `dice_simulator()` with an integer parameter called `n`. This function should create a list of integers 1 through 6 and randomly sample this list with replacement `n` times. The function should return the `n` samples as a list or numpy array. Note that `n` should be a positive integer (2 pt).

Define a function called `proportions()` to calculate what proportion of the "rolls" that are 1s, 2s, 3s, 4s, 5s, and 6s. Print these 6 proportions. `proportions()` should have a single parameter called `rolls`, which should take in the output of `dice_simulator()` (3 pt).

Define a function called `three_streak()` to calculate the maximum number of times 3 was "rolled" in a row and print this value. To be in a row, the 3's have to be next to each other in a list (such as if `rolls[1]` and `rolls[2]` are both 3). Like `proportions()`, `three_streak()` should have a single parameter called `rolls`, which should take in the output of `dice_simulator()` (3 pt). 
- *Hint: `max()` is a built in function in Python that finds the largest value in a list.*

Define a function called `simulation()` that calls `dice_simulator()`, `proportions()`, and `three_streak()`. Make sure that `proportions()` and `three_streak()` are called so that they use the same dice rolls. `simulation()` should take a single parameter `n` that is fed into `dice_simulator()`. Have this function print the value of n, as well (1 pt). 

Call `simulation()` several times with the `n` parameter at different values (1 pt). 





In [61]:
import numpy as np

def dice_simulator(n):
    if type(n) is not int or n < 1: 
        return "n is not a postive integer"
    l = [i + 1 for i in range(6)] # Creates a list with every number from 1 to 6
    return np.random.choice(l, n) # Returns n random choices from the list l

def proportions(rolls):
    a = np.array([0, 0, 0, 0, 0, 0]) 
    for i in range(len(rolls)): # Increments the value of the index of the array that corresponds for each number from 1 to 6
        a[rolls[i] - 1] += 1
    return a/len(rolls) # Returns the array with a count of how many times each number was rolled divided by the total rolls.

def three_streak(rolls):
    curr_streak = 0
    streaks = np.array(rolls)  # Creates a new array that is equal to and the same length as rolls
    
    # Iterates over the entire rolls array
    for i in range(len(rolls)):
        if (rolls[i] == 3): # If the roll was a three, the streak is incremented by 1
            curr_streak += 1
        else:
            curr_streak = 0 # If the roll is not a three, the streak is reset to 0.
        streaks[i] = curr_streak # Each spot in the streaks array is assigned to the streak of threes at that index of rolls
    return np.max(streaks) # Returns the largest streak

def simulation(n):
    print(n)
    rolls = dice_simulator(n)
    prop = proportions(rolls)
    threes = three_streak(rolls)
    print (rolls)
    print (prop)
    print (threes)


# Test cases
simulation(5)
simulation(9)
simulation(20)
simulation(100)


5
[1 1 5 3 6]
[0.4 0.  0.2 0.  0.2 0.2]
1
9
[2 6 3 4 1 1 2 4 5]
[0.22222222 0.22222222 0.11111111 0.22222222 0.11111111 0.11111111]
1
20
[3 4 4 1 6 4 4 3 3 2 2 4 6 1 1 2 2 3 5 2]
[0.15 0.25 0.2  0.25 0.05 0.1 ]
2
100
[2 3 2 4 6 2 6 5 6 4 5 5 6 2 2 4 3 2 1 2 3 6 2 2 4 6 1 4 3 3 4 6 6 4 5 2 2
 6 4 5 5 4 5 6 1 5 6 4 3 5 3 4 2 5 2 2 2 3 4 3 2 3 2 6 2 4 4 5 2 6 4 6 5 6
 3 3 3 5 3 6 2 4 1 3 4 1 3 5 2 4 3 1 4 1 6 4 5 1 4 4]
[0.08 0.21 0.17 0.22 0.15 0.17]
3
